### ISSUE TITLE
Pass access token via env instead of password

### ISSUE THREAD

**Issue by ptman** [livematrix/server#5]
To prevent a login/session on each restart.

**Comment by osousa** [comment]
It now stores the session token on the database. To define the number of days to keep the same Access_Token, edit the .env file: 

```
# Time to wait until next login (in days)
MATRIX_TIMEOUT=7

```
It will retry to Login after 7 days, or if the token becomes invalid, and stores the new session replacing the old one. 

Thank you for your input!

**Comment by ptman** [comment]
I would recommend a strategy where a new login is tried if the access token doesn't work. By default they don't expire. And when expiration is added, it will be communicated clearly via the API

**Comment by osousa** [comment]
I don't know if i understood correctly what you meant, but at the moment, it happens like this:

- It looks up for a token on the database
- If there's no token, it uses credentials to login  (3 tries)
- if there's a token and is invalid or wrong, it falls back to using credentials  (3 tries)
- each time credentials are used, it stores the new token created
- If the token exists and is valid, it uses this for session. 

If one wishes to never login as long as there's a token, MATRIX_TIMEOUT could be set to 99999 days

Thanks!
